#Specify profiles
spring:
  profiles:
    active: dev

# mail sender through the Java Mail sender
  mail:
    host: smtp.gmail.com
    port: 587
    username: anupmugabasav1999@gmail.com
    password: dhmq bpeq njin uljk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#Specify logging level
logging:
  level:
    com:
      anup:
        v1:
          JournalApp: DEBUG

weather:
  api:
    key: c3cda83f8e152b8cfc5ab59450c04217